app:
  jwt:
    secret: "change-me-to-a-long-random-secret-at-least-32-chars"
    expirySeconds: 86400

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/booking
    username: app
    password: app

  kafka:
    bootstrap-servers: localhost:9092

  data:
    redis:
      host: localhost
      port: 6379